### ISSUE TITLE
Controller changes

### ISSUE THREAD

**Issue by orbea** [GLupeN64/GLupeN64#159]
Is it possible to make the changes in commit 16c2f4ab5fed84c6a639e470086ba62f40c4313c configurable so that some can have the old defaults? Honestly it really bugs me that GLupeN64 has one behavior and RetroArch has another. Sure mupen64plus upstream is doing what you are doing now, but personally I much prefer how RetroArch and mupen64plus-libretro are doing it. :)

**Comment by loganmc10** [comment]
what do you mean by "configurable"? Isn't is already configurable via button remapping?

**Comment by loganmc10** [comment]
Also I wouldn't say that GLupeN64 has one behavior and RetroArch has another. The cores are free to map the buttons as they please, there is no "rule" that the RetroPad "A" button must be mapped to whatever button the emulated system happened to call "A".

For instance, if the OG Xbox was ever added to RetroArch, I wouldn't expect RetroPad A to be mapped to Xbox A, I would expect RetroPad A = Xbox B, since that is physically where the button was on the original console.

**Comment by orbea** [comment]
Yes, you are right. I did not properly look at `Controls` under the quick menu before and core overrides are capable of saving the difference. That said wouldn't it be better to return to the old defaults to avoid inconsistency with RetroArch and other cores and instruct anyone who wants the new behavior to use core ovverrides? If not, its not a big deal and this can be closed. Thanks. :)

**Comment by loganmc10** [comment]
This is probably one of those things where everyone is going to have a different opinion (for instance see https://github.com/libretro/mupen64plus-libretro/issues/405)

Again, the only thing it is inconsistent with is mupen64plus-libretro, it's not really accurate to say it's inconsistent with _RetroArch_, since mapping is left up to the cores. It is however consistent with mupen64plus

**Comment by orbea** [comment]
Well, that is fair enough. I'm just quite used to and fond of the Japanese default controller binds that RetroArch and most cores use by default, that is accept is the right button and cancel is the bottom. We can leave it at that, remaps are satisfactory enough. :)
