### ISSUE TITLE
Option to use RetroPad A and B buttons for "A" and "B"

### ISSUE THREAD

**Issue by tony971** [GLupeN64/GLupeN64#166]
While I agree that on a standard xbox or ps controller, using the RetroPad B and Y buttons for "A" and "B" makes the most sense, this layout is unusable for N64 controllers and their clones. N64 controllers don't use the RetroPad X or Y buttons. The C buttons are mapped as the right joystick. If you map the N64 controller's "A" and "B" buttons as "B" and "Y", then there is no longer a mapping for "A" to use in the RetroArch menu.

**Comment by loganmc10** [comment]
I'm not quite sure what you mean. Can't you just remap the buttons in the "control" menu in "quick settings"?

**Comment by tony971** [comment]
The issue with that is that it doesn't do it generically. It sets "A" and "B" to button numbers. Those no longer work when you switch controllers. The way you set your C buttons in relation to a retropad is a much more universal solution.

**Comment by loganmc10** [comment]
I'm still not exactly sure what the issue is>

> If you map the N64 controller's "A" and "B" buttons as "B" and "Y", then there is no longer a mapping for "A" to use in the RetroArch menu.

I am talking about a core remapping. If you go "Quick Menu" > "Controls". The remappings there only affect the core, it shouldn't affect navigating through the menus.

> The issue with that is that it doesn't do it generically. It sets "A" and "B" to button numbers. Those no longer work when you switch controllers.

I don't know if I understand exactly what you're saying. You are saying that if you remap them, then switch controllers, it no longer works? If you remap N64 A to RetroPad A, if you switch controllers, that's what it will be for the new controller.

**Comment by tony971** [comment]
> If you remap N64 A to RetroPad A, if you switch controllers, that's what it will be for the new controller.

This is not what happens when you use Quick Menu -> Controls. You set N64 controls to your controller's buttons. Not RetroPad buttons. You can see this when you check the new core remap file.

**Comment by orbea** [comment]
This has been discussed already, personally I found remaps satisfactory, but maybe I'm missing something too?

https://github.com/GLupeN64/GLupeN64/issues/159

**Comment by tony971** [comment]
Like I said, if you use remaps, your remap is set to a controller button number. So when you switch controllers, the remap gets all screwed up because that controller's button numbers aren't the same. Remaps don't remap RetroPad layouts. They statically set keys/button numbers.

**Comment by loganmc10** [comment]
@tony971 What solution are you proposing?

This still seems to be a RetroArch issue, perhaps remaps should be controller specific. Are you asking me to revert it back to the way it was before, or do you have some other solution?

**Comment by tony971** [comment]
Well your core options for the C buttons are generic enough to apply across multiple controllers. Core options for A and B, implemented in a similar fashion, would be ideal.

Maybe it would even make sense to remove the core options for the C buttons and only have core options for A and B. Since people are less likely to change the C buttons (all controllers that utilize the button switching have similar layouts).

**Comment by loganmc10** [comment]
I think having core options to map A and B is a little clumsy. The C buttons are there because there are no C buttons on the "RetroPad" controller.

Remapping the buttons to work with a replica N64 works fine, your only issue is that when you change controllers, the remapping no longer works. That is an issue with RetroArch and how it handles button remapping. They could implement a per-controller remapping system, or have the remapping apply to the "RetroPad" buttons and not the actual controller buttons.

**Comment by tony971** [comment]
@twinaphex @fr500

**Comment by fr500** [comment]
uh... it already applies to the retropad.

**Comment by tony971** [comment]
Am I just interpreting the .rmp file wrong when it lists a button number?

**Comment by fr500** [comment]
that's the retropad button id

**Comment by tony971** [comment]
Okay so I was interpreting it wrong. Sorry for being a public idiot. I'm out of town and only brought one controller with me.
