### ISSUE TITLE
Netplay problem

### ISSUE THREAD

**Issue by fr500** [GLupeN64/GLupeN64#167]
For some reason when netplay is started Glupen starts flushing stuff like this:

RetroArch [INFO] :: Environ SYSTEM_DIRECTORY: "..\..\EmulatorData\System".
RetroArch [libretro INFO] :: mupen64plus: Saved state to: savestate.temp
RetroArch [INFO] :: Environ SYSTEM_DIRECTORY: "..\..\EmulatorData\System".
RetroArch [libretro INFO] :: mupen64plus: Saved state to: savestate.temp
RetroArch [INFO] :: Environ SYSTEM_DIRECTORY: "..\..\EmulatorData\System".
RetroArch [libretro INFO] :: mupen64plus: Saved state to: savestate.temp
RetroArch [INFO] :: Environ SYSTEM_DIRECTORY: "..\..\EmulatorData\System".
RetroArch [libretro INFO] :: mupen64plus: Saved state to: savestate.temp
RetroArch [INFO] :: Environ SYSTEM_DIRECTORY: "..\..\EmulatorData\System".
RetroArch [libretro INFO] :: mupen64plus: Saved state to: savestate.temp
RetroArch [INFO] :: Environ SYSTEM_DIRECTORY: "..\..\EmulatorData\System".
RetroArch [libretro INFO] :: mupen64plus: Saved state to: savestate.temp
RetroArch [INFO] :: Environ SYSTEM_DIRECTORY: "..\..\EmulatorData\System".
RetroArch [libretro INFO] :: mupen64plus: Saved state to: savestate.temp
RetroArch [INFO] :: Environ SYSTEM_DIRECTORY: "..\..\EmulatorData\System".
RetroArch [libretro INFO] :: mupen64plus: Saved state to: savestate.temp
RetroArch [INFO] :: Environ SYSTEM_DIRECTORY: "..\..\EmulatorData\System".
RetroArch [libretro INFO] :: mupen64plus: Saved state to: savestate.temp
RetroArch [INFO] :: Environ SYSTEM_DIRECTORY: "..\..\EmulatorData\System".
RetroArch [libretro INFO] :: mupen64plus: Saved state to: savestate.temp
RetroArch [INFO] :: Environ SYSTEM_DIRECTORY: "..\..\EmulatorData\System".
RetroArch [libretro INFO] :: mupen64plus: Saved state to: savestate.temp
RetroArch [INFO] :: Environ SYSTEM_DIRECTORY: "..\..\EmulatorData\System".
RetroArch [libretro INFO] :: mupen64plus: Saved state to: savestate.temp
RetroArch [INFO] :: Environ SYSTEM_DIRECTORY: "..\..\EmulatorData\System".
RetroArch [libretro INFO] :: mupen64plus: Saved state to: savestate.temp
RetroArch [INFO] :: Environ SYSTEM_DIRECTORY: "..\..\EmulatorData\System".
RetroArch [libretro INFO] :: mupen64plus: Saved state to: savestate.temp
RetroArch [INFO] :: Environ SYSTEM_DIRECTORY: "..\..\EmulatorData\System".
RetroArch [libretro INFO] :: mupen64plus: Saved state to: savestate.temp
RetroArch [INFO] :: Environ SYSTEM_DIRECTORY: "..\..\EmulatorData\System".
R

**Comment by fr500** [comment]
hmmm I realize the problem, you're saving to a temporary location then copying the data over...
any particular reason for this approach?

**Comment by fr500** [comment]
I tried (and failed) to make libretro functions for savestates.
Saving seems easy enough...

But loading uses gzip all over the place instead of just at the end...
https://hastebin.com/mifosaqapu.diff

**Comment by loganmc10** [comment]
I did this so that I could use the upstream savestate code, I've tried as much as possible to not deviate from their code. Their save state code only accepts a file path as an argument and they handle opening the file and whatnot, hence the temporary file.

So this could be fixed by refactoring the upstream save state code and seperating out the file opening code, and having the savestate function just write to a stream (which could be a file stream in their case, or a memory stream in ours)

I've never really looked into it much since the current method has been good enough. Is netplay practical for mupen64plus? How does it work with mupen64plus-libretro?

**Comment by fr500** [comment]
I got a bit further but it's crashing now :p
https://hastebin.com/ujozegajer.diff

**Comment by fr500** [comment]
Regarding mupen, it doesn't really work yet, but I still think this is something worthy to fix.
We avoid I/O like the plague and it just seems ugly to save, then read the file to save it again...

I think I'm 90% there... but not sure
https://gist.github.com/fr500/c16a5f1a7e191706fd13bbd2f55ac8d3

**Comment by twinaphex** [comment]
This is never going to be performant enough if your serialization functions have to read/write to a file on disk, also, adding further compression then to the mix will make serialization even slower.

You will have to write non-file I/O versions of load/save state functions, like what was done for the mupen64 libretro port, otherwise it's always going to suck for either rewinding or netplay purposes.

**Comment by loganmc10** [comment]
I agree, if I see that mupen64plus-libretro has good netplay performance I'll look into it. I would submit a pull request to mupen64plus-core because I don't want to mantain my own save state code. I don't want to do that unless I can see that there will be a noticeable difference to the users

**Comment by twinaphex** [comment]
I don't know why you are so beholden to upstream though. These are codebase maintainers who barely understand the code they are modifying. Which isn't strange, since 99.9% of that code was written by Hacktarux, and the last time he wrote a single line of code for Mupen64 must be dating back to at least 10+ years ago.

It's reasons like this and the sheer ignorance whenever i was talking to them that led to me simply not caring anymore and going my own way. I will never, ever sacrifice the quality of libretro ports just because of certain coders on 'upstream' who are not reasonable enough to listen to problems I have with a codebase, and don't want to talk about ways that we could both find a common solution. I tried this many times but if I see a bunch of coders who are honestly underqualified to know what they are doing basically waste my time and not even have the honesty to tell me they basically don't know how to do it, I move on. I have better stuff to do then.

**Comment by fr500** [comment]
@loganmc10 even without netplay, this is probably bad for rewind, and it's just wasteful.
That said, it's your project I won't insist.

**Comment by fr500** [comment]
@loganmc10 I figured it out, do you want me to send a PR?

**Comment by loganmc10** [comment]
@twinaphex I disagree with your assessment of the upstream programmers. Both Gillou68310 and bsmiles32 still make many large contributions to the project.

I think following the upstream project is the right way to do it. You don't have to look any further than the PPSSPP core to see why I feel this way.

I'll give you an example why I feel it's important to do it this way: there are 2 PR's waiting in mupen64plus-core right now, 213 and 227. They both modify savestates.c. After those PR's are merged, bsmiles32 is going to merge support for Transfer Paks. Who is going to keep savestates.c up to date so that it all compiles and works after those PR's? Me? I don't want to spend my time fiddling with code like that.

I agree that the current system of temporary files sucks, but I think it's better than maintaining my own code. Anyone is free to refactor the upstream savestates.c to make it work properly. I'll even submit the PR to them if you guys don't want to deal with them.

**Comment by twinaphex** [comment]
You think it's better that you wear out SSDs this way when they try to do rewinding? Or that performance is 2fps instead of 90? I don't know what to say dude honestly. At its current state, you are actively doing harm to the lifespan of SSDs itself by letting it stay this way.

BTW, I never said anything about bsmiles32, he was actually the only reasonable person out of them all that even wanted to work with me. And coincidentally one of the few who knows what he is doing.

I'm not going to respond to the whole bait of PPSSPP, there are reasons for that which you don't know about, don't understand and for which I require you no explanation for, and they have to do with us having different priorities for what we needed to work on. And sometimes not everything upstream does is always necessarily better, sometimes there is no real reason to upgrade. If you feel it's so important, go ahead and start pulling your weight and do it instead.

**Comment by twinaphex** [comment]
Anyway, we are going to do a shallow fork, you want us to jump through hoops with upstream which means we can wait until the cows come home before anything gets merged. 

No thanks, we need to get stuff done here, and we need to get it done now. I have no time for fillibusters or nonsense. I don't have time to wait months for it or even years.

**Comment by loganmc10** [comment]
Well I'm sorry you feel that way. I'm not going to work on a forked project, I'll be directing my free time to improving GLideN64 and mupen64plus and I'll be abandoning this project.

**Comment by fr500** [comment]
It's not being forked out of spite or anything....
It's a shallow fork which would just pull changes from yours...

I really don't understand this scene...

**Comment by fr500** [comment]
The changes in those 2 PRs here are nothing that would need a massive rewrite
https://github.com/bsmiles32/mupen64plus-core/blob/352559f92b38e61e61330bbc96539dabefcf4377/src/main/savestates.c

https://github.com/bsmiles32/mupen64plus-core/blob/6661d2c9436ba2a09320235b2eac7814607f5c16/src/main/savestates.c

**Comment by twinaphex** [comment]
Github has a 'fork' button for a reason. If you are against people forking, you are essentially against open source to begin with.

We are only merging this PR in our 'shallow fork', everything else we keep the same. It's not going to cause big merge conflicts.

**Comment by loganmc10** [comment]
@twinaphex the true strength of open source is that people can work collaboratively with each other on a project. To me the fork button is there so that people can fork the project, make their changes, and submit their work back to the project, something you rarely, if ever do. So I think it is you that is "against open source".

To completely fork a project because of such a minor issue as save state performance seems silly to me, especially since a fix could easily be sent to mupen64plus-core, and yes, you would probably have to wait a week or two for it to be merged.

**Comment by fr500** [comment]
The issue is not minor at all though.. it's a big roadblock for netplay and it makes rewind completely unusable.

I see you even mentioned this on your wiki.

I already opened an issue there and asked for feedback, as I said I'm more than willing to backport once those PRs are merged.

**Comment by twinaphex** [comment]
@loganmc10 I do put hardware in your hands to get development done, though. Yeah I am so against open source, by allowing you to do stuff and even getting some free toys to play with at the same time. I think the proof is in the pudding there.

You are not in a position where you get to judge my affiliation to 'open source' in any way, shape or capacity. I suggest you dial it back a notch and realise just how childish and irrational you are behaving right now. We are talking about two functions right now that is in a PR, which is merged in our 'shallow fork'. That is the 'extent' of this fork.

Meanwhile, what you suggest we should do in the upcoming two, three weeks is -
- Have serialization at 2fps, do 4MB transfers per second which will wear SSDs lifespan down like a motherfucker for no reason other than 'I don't want to diverge from muh precious upstream, muh precious!!!!!'
- Have us not being able to use netplay at all until a time where your 'precious upstream' finally deems it can finally be merged.

I know that project better than you, and I was involved years before you even came here, and I know exactly what 'traction' it will get. I'm not wasting my time on that bullshit.

**Comment by twinaphex** [comment]
@loganmc10 If we give up the shallow fork and let you conduct this with upstream, will you reconsider? I can't lie and say I agree with your stance, I think it is backwards, but all the same I don't want to lose you as a contributor and I respect what you have brought to the table before.

**Comment by twinaphex** [comment]
I deleted the previous post too not to hide what I said, but because it will hopefully reflect that I intend to make this work and I'm willing to take back what I said before.

**Comment by twinaphex** [comment]
I've removed the shallow fork. I ask you again to reconsider. I have done my part at least.

**Comment by loganmc10** [comment]
I think it'd be best for me to move on to other things. If there was any financial cost to the hardware I was sent you can email me the details and I'll reimburse you. Hopefully somebody can pickup where I left off with this project. Maybe they can even come up with a more original name lol.

**Comment by twinaphex** [comment]
Can't you just come to IRC so we can briefly discuss this? Back and forth on a forum is what makes some minor mosquito issue like this blow up into something like this which is really unnecessary. This is not the way how you rectify a situation like this, so let's try real-time chat instead, this is not working.

**Comment by twinaphex** [comment]
I don't need to be reimbursed for anything, it was given without any expectation. What I do ask for you though is to give us a chance and to not just walk away like this while we are essentially offering a truce already, that is just making things even more unreasonable in my book. I have treated you more than fair, I ask simply that you return the favor and that we talk this over like civilized adults on a medium that lends itself to real-time chat.

**Comment by twinaphex** [comment]
Look, to be perfectly frank with you, we want to launch RA 1.4.0 first and having USABLE netplay with an N64 core would be killer.

THAT is what the haste was about.

We wasted nearly an entire day now on this crap and you made a huge issue over some 'shallow fork' that we had NO INTENTION AT ALL of making some kind of 'non-shallow' fork. It was ALWAYS going to be just about a 1 PR that is merged temporarily while you do the 'proper' thing and find a way to get upstream to implement this on their side.

Do we really need to be having a long drawn out fight over something like that and then you leaving a project over that? This is such an extreme and unnecessary overreaction to this, please try to understand our side of things here.

**Comment by SigmaVirus** [comment]
It's really sad to see this project disappear forever, this was the only N64 emulator/N64 core that were worth using.

This marks a sad day in N64 emulation history...

**Comment by twinaphex** [comment]
@SigmaVirus This situation got resolved yesterday, the project is not dead!

**Comment by loganmc10** [comment]
Ya we sorted it out, sorry to freak everyone out lol

**Comment by SigmaVirus** [comment]
Yay GLupeN64 lives again!!!
