### ISSUE TITLE
...

### ISSUE THREAD

**Issue by orbea** [GLupeN64/GLupeN64#172]
https://github.com/GLupeN64/GLupeN64/commit/04adfb2fed84a2ce725b955d62d9e24b52c60a50

What's up? Does it have to turn out this way? :(

**Comment by orbea** [comment]
@loganmc10 I just want to say that GLupeN64 is clearly the most useful n64 emulator today, thanks for all your time working with it, but I'm still rather sad that its potentially short lived...

**Comment by loganmc10** [comment]
yeah I've been quite happy with it, but libretro and I just don't seem to mesh well. I'm going to spend my time trying to improve GLideN64 and mupen64plus. I've been backporting the improvements here into the upstream projects (VBO's in the refactor_graphics branch, GLideN64.custom.ini support in mupen64plus, etc...)

I'm also going to work on a new mupen64plus frontend, since I can't even get m64py working on my laptop, we'll see how far I get with that, so hopefully all these things will mean a better experience with mupen64plus for people.

**Comment by orbea** [comment]
I won't lie, my interest to spend time debugging will greatly diminish without libretro. I suspect that is difference in issues like https://github.com/gonetz/GLideN64/issues/1322 which have only become worse with the refactor branch, but are still entirely absent in GLupeN64. It'd be rather sad to see that go. Is there any way the disagreements can be resolved without needing to reinvent the frontend? I understand that w/e drama I luckily avoided is quite discouraging, but if I may be blunt I think there are some things worth more than that and you've done great with it so far...

**Comment by loganmc10** [comment]
Ya I'm not sure what is up with Winback, I don't think I did anything special in glupen64 to fix that.

Anyway no I don't think there is anything that can be done. It's just not a project I'll enjoy working on anymore.

I'm not planning on doing anything crazy with the frontend, hopefully just implement a GTK frontend that matches m64py for features, but works... I'm hoping it can get integrated into the mupen64plus-ui-console repo, and it'll just get built if the system has GTK installed. Then they can be distributed as mupen64plus and mupen64plus-gtk or something, similar to how Transmission is normally packaged.

**Comment by SigmaVirus** [comment]
As already been said here its sad to see this project die so soon, GLupeN64 is the only N64 emulator/core I use today and it's the only one that's worth using to begin with because of 3 reasons:
1. It's easy and simple to use/setup
2. You don't have to fiddle around with plugins etc. and everything is baked in
3. Best N64 experience with little to none issues

Thanks for everything @loganmc10 

Until something drastic happens in the N64 emulation scene, the last official, non-forked GLupeN64 build will be the only thing I will use for my N64 needs.

**Comment by loganmc10** [comment]
@SigmaVirus once I get the frontend working I plan on distributing a zip file with mupen64plus+GLideN64 for Windows and Linux, so it should just be "unzip and play", hopefully that will provide a similar experience for people as this did, minus some things like shader support

**Comment by orbea** [comment]
If I may be blunt without intending offense...

The only thing that ever made GLideN64 or mupen64plus at all worth using was libretro and it goes far beyond shaders. Where else will you find quality drivers? (It won't be SDL2) How about kms support? Or the highly reduced use of dependencies? And yes, there is still mupen64plus-libretro, but that was quickly shown to not be worth much besides testing accuracy in angrylion and the potential of parallel (Not that anyone is really working on it or even can use it). So without an actually maintained libretro N64 core that is willing to work with upstream N64 emudevs there is suddenly isn't any n64 emulator worth a damn. There is no gtk, qt, wxwidgets or etc frontend that can surpass the amount of effort that gone into RetroArch nor its ambition to do what no one else would even dare.

Now I realize that there seems little point in changing your mind and I understand your decision to a degree, but its outright depressing that all the time that has gone into GLupeN64 is just going up in smoke because of some stupid drama that happened at a cesspit like reddit which is not even worth caring about.

My proposed solution is to burn reddit to the ground. ;)

Seriously, I will continue using GLupeN64 as well and hope that someone with the capability and interest in maintaining GLupeN64 comes along before it ends up like VisualBoyAdvance.

Thanks for the fish, I wish you the best in w/e you decide.

**Comment by loganmc10** [comment]
Trust me I won't be offended, and you've certainly helped out enough to have an opinion on this. RetroArch does have a lot going for it, unfortunately I just don't find it enjoyable to work with/develop for.

I also hope someone else will pick up on this work, I'd certainly be happy to consult with them and help, and hand over commit access to this repo.

**Comment by SigmaVirus** [comment]
Thanks @loganmc10
 
The thing I loved most with using GLupeN64 in RetroArch however was the usage of shaders because it were through shaders I could get an authentic N64 look and feel which no other emulator have ever given me.

Well the future and new things have to wait anyway because right now GLupeN64 and RetroArch is all I need for my N64 play troughs.

**Comment by pdanilew** [comment]
Ok, now I'm surprised.

I found this project a week ago and was able to run it quite quickly comparing to other RetroArch related N64 things (on RPI3). I though I might help somehow and now I see it is closed.
It's a pitty but thanks for a great work!

**Comment by orbea** [comment]
Its time to close this.

https://github.com/libretro/mupen64plus-libretro

Also, upstream GLideN64 has regressed heavily since this issue was started...
